runtime: go
api_version: go1

handlers:
# #[START gae_go_env_static_handlers]
# Otherwise, find file in static directory
- url: /static
  static_dir: static
  secure: always

# #[END gae_go_env_static_handlers]  
- url: /.*
  script: _go_app
  secure: always
